name: GeoCN Docker Image CI

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 2 15 * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }} 

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set registry environment variable
        run: echo "REGISTRY=ghcr.io" >> $GITHUB_ENV
      
      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Get latest mihomo
        run: |
          LATEST_VERSION=$(curl -s https://api.github.com/repos/MetaCubeX/mihomo/releases/latest | jq -r '.tag_name')
          curl -s https://api.github.com/repos/MetaCubeX/mihomo/releases/latest | jq -r '.assets[] | select(.name | test("^mihomo-linux-amd64-v.*gz$")) | .browser_download_url' | xargs -I {} wget {}
          gzip -d *.gz && mv mihomo-* mihomo
          echo "LATEST_VERSION=$LATEST_VERSION" >> $GITHUB_ENV

      - name: Build 和 push Docker image
        uses: docker/build-push-action@v6
        with:
          push: true
          context: .
          tags: |
            ${{ env.REGISTRY }}/${{ github.repository }}:latest
            ${{ env.REGISTRY }}/${{ github.repository }}:${{ LATEST_VERSION }}
          platforms: linux/amd64
