name: Mihomo Docker Image CI

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      REGISTRY: ghcr.io

    steps:
      - uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver-opts: network=host
      
      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
    
      - name: Get latest mihomo
        run: |
          LATEST_RELEASE=$(curl -s https://api.github.com/repos/MetaCubeX/mihomo/releases/latest)
          LATEST_VERSION=$(echo "$LATEST_RELEASE" | jq -r '.tag_name')
          DOWNLOAD_URL=$(echo "$LATEST_RELEASE" | jq -r '.assets[] | select(.name | test("^mihomo-linux-amd64-v3.*\\.gz$")) | .browser_download_url')
          wget -q "$DOWNLOAD_URL" && gunzip $(basename "$DOWNLOAD_URL") && mv mihomo-* mihomo && chmod +x mihomo
          ls -lha
          echo "LATEST_VERSION=$LATEST_VERSION" >> $GITHUB_ENV

      - name: Build 和 push Docker image
        uses: docker/build-push-action@v6
        with:
          push: true
          context: .
          tags: |
            ${{ env.REGISTRY }}/${{ github.repository }}:latest
            ${{ env.REGISTRY }}/${{ github.repository }}:${{ env.LATEST_VERSION }}
          platforms: linux/amd64
